"""Local SQLite history of every license generated by the License Manager."""

from __future__ import annotations

import os
import sqlite3

import licensing_core as core

_DB_PATH = os.path.join(core.data_dir(), "licenses.db")
_conn: sqlite3.Connection | None = None

_SCHEMA = """
CREATE TABLE IF NOT EXISTS licenses (
    id             INTEGER PRIMARY KEY AUTOINCREMENT,
    clinic_name    TEXT DEFAULT '',
    customer_phone TEXT DEFAULT '',
    city           TEXT DEFAULT '',
    machine_id     TEXT NOT NULL,
    license_type   TEXT NOT NULL,
    demo_days      INTEGER,
    patient_limit  INTEGER DEFAULT 0,
    generated_date TEXT NOT NULL,
    expiry_date    TEXT,
    product_key    TEXT NOT NULL,
    license_path   TEXT DEFAULT '',
    created_at     TEXT DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS idx_lic_clinic ON licenses(clinic_name);
CREATE INDEX IF NOT EXISTS idx_lic_phone  ON licenses(customer_phone);
CREATE INDEX IF NOT EXISTS idx_lic_mid    ON licenses(machine_id);
"""


def _get() -> sqlite3.Connection:
    global _conn
    if _conn is None:
        _conn = sqlite3.connect(_DB_PATH)
        _conn.row_factory = sqlite3.Row
        _conn.executescript(_SCHEMA)
        _conn.commit()
    return _conn


def add(record: dict) -> int:
    conn = _get()
    cur = conn.execute(
        """INSERT INTO licenses
           (clinic_name, customer_phone, city, machine_id, license_type,
            demo_days, patient_limit, generated_date, expiry_date,
            product_key, license_path)
           VALUES (?,?,?,?,?,?,?,?,?,?,?)""",
        (record.get("clinic_name", ""), record.get("customer_phone", ""),
         record.get("city", ""), record["machine_id"], record["license_type"],
         record.get("demo_days"), record.get("patient_limit", 0),
         record["generated_date"], record.get("expiry_date"),
         record["product_key"], record.get("license_path", "")),
    )
    conn.commit()
    return int(cur.lastrowid)


def search(term: str = "", type_filter: str = "ALL") -> list[sqlite3.Row]:
    conn = _get()
    where = []
    params: list = []
    term = (term or "").strip()
    if term:
        like = f"%{term}%"
        where.append("(clinic_name LIKE ? OR customer_phone LIKE ? "
                     "OR machine_id LIKE ?)")
        params += [like, like, like]
    if type_filter in (core.TYPE_DEMO, core.TYPE_FULL):
        where.append("license_type = ?")
        params.append(type_filter)
    sql = "SELECT * FROM licenses"
    if where:
        sql += " WHERE " + " AND ".join(where)
    sql += " ORDER BY id DESC"
    return conn.execute(sql, params).fetchall()
